---
- name: RETRIEVE WORKER NODE DETAILS FROM KUBERNETES NODE
  hosts: localhost
  gather_facts: no

  collections: 
    - kubernetes
  
  tasks:
    - name: GET WORKER NODE DETAILS
      k8s_info:
        kind: Node
        namespace: default
      register: node_result
    
    - name: DISPLAY OUTPUT
      debug:
        msg: "{{ node_result }}"
    
    - name: SET VARIABLE STORING EKS WORKER NODE ADDRESS
      set_fact:
        worker_address: "{{ node_result | json_query(query) }}"
      vars:
        query: "resources[].status.addresses"
  
    - name: DISPLAY EKS WORKER ADDRESS
      debug:
        msg: "{{ worker_address }}"