---
- name: RETRIEVE WORKER NODE DETAILS FROM KUBERNETES NODE
  hosts: localhost
  gather_facts: no

  collections: 
    - kubernetes
  
  tasks:
    - name: GET WORKER NODE DETAILS
      k8s_info:
        kind: Node
        namespace: default